name: Collect-Information  # Name of your workflow

on:
  schedule:
    - cron: '0 0 * * *'  # Runs the workflow daily at midnight

jobs:
  collect-information:
    runs-on: ubuntu-latest  # Specifies the type of machine the job will run on
    
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2  # Sets up Python on the runner
        with:
          python-version: '3.x'  # Specifies the Python version to be used

      - name: Checkout code
        uses: actions/checkout@v2  # Checks out your repository's code
        
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas requests tqdm gspread oauth2client selenium chromedriver_autoinstaller

      - name: Run Python script
        run: python your_script.py  # Replace `your_script.py` with the name of your Python script
