run-name: Collect Information  # Name of your workflow

on: [push]
         
jobs:
  collect-information:
    runs-on: ubuntu-latest  # Specifies the type of machine the job will run on
    
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2  # Sets up Python on the runner
        with:
          python-version: '3.11'  # Specifies the Python version to be used

      - name: Checkout code
        uses: actions/checkout@v2  # Checks out your repository's code
        
      - name: Update apt-get
        run: sudo apt-get update -y
  
      - name: Install Required Libraries
        run: |
          sudo apt-get install -y \
          libglib2.0-0 \
          libnss3 \
          libdbus-glib-1-2 \
          libgconf-2-4 \
          libfontconfig1 \
          gconf2-common \
          libwayland-server0 \
          libgbm1 \
          udev \
          libu2f-udev \
          libjsoncpp25 \
          libxnvctrl0
  
      - name: Fix Broken Dependencies
        run: sudo apt --fix-broken install -y
          
      - name: Install Required Module
        run: |
          python -m pip install --upgrade pip
          pip install undetected-chromedriver selenium selenium-wire selenium_authenticated_proxy selenium_stealth gspread gspread_dataframe tqdm oauth2client kaggle zipfile

      - name: Setup Kaggle
        run: |
          mkdir $HOME/.kaggle
          echo '{"username":"${{ secrets.KAGGLE_USERNAME }}","key":"${{ secrets.KAGGLE_KEY }}"}' > $HOME/.kaggle/kaggle.json
          chmod 600 $HOME/.kaggle/kaggle.json
          
      - name: Import Module
        env:
          authorization_whapi: ${{ secrets.AUTHORIZATION_WHAPI }}
          group_id: ${{ secrets.GROUP_ID }}
          mycredential: ${{ secrets.MYCREDENTIAL }}
          proxy_link: ${{ secrets.PROXY_LIST_LINK }}
          spreadsheet_link: ${{ secrets.SPREADSHEET_LINK }}
        run: |
         #Secret
         import os
         authorization_whapi = os.environ['authorization_whapi']
         group_id = os.environ['group_id']
         mycredential = os.environ['mycredential']
         proxy_link = os.environ['proxy_link']
         spreadsheet_link = os.environ['spreadsheet_link']
         
         from seleniumwire import webdriver
         from selenium.webdriver.common.by import By
         from selenium.common.exceptions import TimeoutException
         from selenium.webdriver.support.ui import WebDriverWait
         from selenium.webdriver.support import expected_conditions as EC
         from selenium.webdriver import ChromeOptions
         from selenium.webdriver.chrome.service import Service
         from selenium.common.exceptions import NoSuchElementException
         from selenium.common.exceptions import InvalidSelectorException
         from selenium.webdriver.common.keys import Keys
         from selenium_stealth import stealth
         from selenium_authenticated_proxy import SeleniumAuthenticatedProxy
         from selenium.webdriver.support.ui import Select
         import random
         import undetected_chromedriver as uc
         import re
         import pandas as pd
         import sys
         import numpy as np
         import time
         from io import BytesIO
         import datetime
         import os
         import requests
         from tqdm.auto import tqdm
         from oauth2client.service_account import ServiceAccountCredentials
         import json
         import gspread
         import math
         from gspread_dataframe import set_with_dataframe
         from zipfile import ZipFile
         import kaggle
         sys.path.insert(0,'/usr/lib/chrome-browser/chromedriver')
         pd.set_option('display.max_columns', None)
         pd.set_option('display.precision', 4)

      - name: Run Script
        run: |
         python keterbukaan-informasi.py
