run-name: Collect Information  # Name of your workflow

on:
  schedule:
    - cron: '0 0 * * *'  # Runs the workflow daily at midnight

jobs:
  collect-information:
    runs-on: ubuntu-latest  # Specifies the type of machine the job will run on
    
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2  # Sets up Python on the runner
        with:
          python-version: '3.11'  # Specifies the Python version to be used

      - name: Checkout code
        uses: actions/checkout@v2  # Checks out your repository's code
        
      - name: Update apt-get
        run: sudo apt-get update -y
  
      - name: Install Required Libraries
        run: |
          sudo apt-get install -y \
          libglib2.0-0 \
          libnss3 \
          libdbus-glib-1-2 \
          libgconf-2-4 \
          libfontconfig1 \
          gconf2-common \
          libwayland-server0 \
          libgbm1 \
          udev \
          libu2f-udev \
          libjsoncpp25 \
          libxnvctrl0
  
      - name: Fix Broken Dependencies
        run: sudo apt --fix-broken install -y
  
      - name: Download Google Chrome
        run: |
          wget -nc -P /usr/lib https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo dpkg -i /usr/lib/google-chrome-stable_current_amd64.deb
  
      - name: Install Chromedriver
        run: |
          wget -nc -P /usr/lib "https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/121.0.6167.85/linux64/chromedriver-linux64.zip"
          sudo unzip -o /usr/lib/chromedriver-linux64.zip -d /usr/lib/chrome-browser/
          sudo apt --fix-broken install -y
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install undetected-chromedriver selenium selenium-wire selenium_authenticated_proxy selenium_stealth gspread gspread_dataframe yfinance

      - name: Run Python script
        env:
          authorization_whapi = ${{ secrets.AUTHORIZATION_WHAPI }}
          group_id = ${{ secrets.GROUP_ID }}
          mycredential = ${{ secrets.MYCREDENTIAL }}
          proxy_link = ${{ secrets.PROXY_LIST_LINK }}
          spreadsheet_link = ${{ secrets.SPREADSHEET_LINK }}
        run: python keterbukaan-informasi.py
