run-name: Collect Information  # Name of your workflow

on: [push]

environment:
  authorization_whapi: ${{ secrets.AUTHORIZATION_WHAPI }}
  group_id: ${{ secrets.GROUP_ID }}
  mycredential: ${{ secrets.MYCREDENTIAL }}
  proxy_link: ${{ secrets.PROXY_LIST_LINK }}
  spreadsheet_link: ${{ secrets.SPREADSHEET_LINK }}
          
jobs:
  collect-information:
    runs-on: ubuntu-latest  # Specifies the type of machine the job will run on
    
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2  # Sets up Python on the runner
        with:
          python-version: '3.11'  # Specifies the Python version to be used

      - name: Checkout code
        uses: actions/checkout@v2  # Checks out your repository's code
        
      - name: Update apt-get
        run: sudo apt-get update -y
  
      - name: Install Required Libraries
        run: |
          sudo apt-get install -y \
          libglib2.0-0 \
          libnss3 \
          libdbus-glib-1-2 \
          libgconf-2-4 \
          libfontconfig1 \
          gconf2-common \
          libwayland-server0 \
          libgbm1 \
          udev \
          libu2f-udev \
          libjsoncpp25 \
          libxnvctrl0
  
      - name: Fix Broken Dependencies
        run: sudo apt --fix-broken install -y
          
      - name: Install Required Module
        run: |
          python -m pip install --upgrade pip
          pip install undetected-chromedriver selenium selenium-wire selenium_authenticated_proxy selenium_stealth gspread gspread_dataframe tqdm oauth2client

      - name: Run Script
        run: python keterbukaan-informasi.py
