run-name: Collect Information  # Name of your workflow

on: [push]
         
jobs:
  collect-information:
    runs-on: ubuntu-latest  # Specifies the type of machine the job will run on
    
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2  # Sets up Python on the runner
        with:
          python-version: '3.11'  # Specifies the Python version to be used

      - name: Checkout code
        uses: actions/checkout@v2  # Checks out your repository's code
        
      - name: Run Script
        env:
          authorization_whapi: ${{ secrets.AUTHORIZATION_WHAPI }}
          group_id: ${{ secrets.GROUP_ID }}
          mycredential: ${{ secrets.MYCREDENTIAL }}
          proxy_link: ${{ secrets.PROXY_LIST_LINK }}
          spreadsheet_link: ${{ secrets.SPREADSHEET_LINK }}
        run: |
         python server-test.py
